# Usa a imagem completa (imagem maior e menos segura)
FROM python:3.12

# Define o diretório de trabalho
WORKDIR /app

# Copia todos o código antes de instalar dependências, invalidando o cache
COPY . .

RUN pip install --upgrade pip

RUN pip install -r requirements.txt # Instala dependências sem fixar versões e como root (pode levar a quebras inesperadas)

#ENV PYTHONUNBUFFERED=1  # Define variáveis de ambiente incompletas, não otimiza a execução

# Expõe porta sem necessidade, já que o container pode mapear automaticamente
EXPOSE 5000 8000

# Usa o servidor Flask nativo, que não é seguro para produção
CMD ["flask", "run"]
